### ISSUE TITLE
alpine-gulp-sass not working

### ISSUE THREAD

**Issue by kisuka** [ellerbrock/docker-collection#6]
I get the following error now when trying to use the alpine-gulp-sass image:

```
gulp_1       | assert.js:374
gulp_1       |     throw err;
gulp_1       |     ^
gulp_1       |
gulp_1       | AssertionError [ERR_ASSERTION]: Task function must be specified
gulp_1       |     at Gulp.set [as _setTask] (/site/node_modules/undertaker/lib/set-task.js:10:3)
gulp_1       |     at Gulp.task (/site/node_modules/undertaker/lib/task.js:13:8)
gulp_1       |     at Object.<anonymous> (/site/gulpfile.js:21:6)
gulp_1       |     at Module._compile (internal/modules/cjs/loader.js:956:30)
gulp_1       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
gulp_1       |     at Module.load (internal/modules/cjs/loader.js:812:32)
gulp_1       |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
gulp_1       |     at Module.require (internal/modules/cjs/loader.js:849:19)
gulp_1       |     at require (internal/modules/cjs/helpers.js:74:18)
gulp_1       |     at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
gulp_1       |   generatedMessage: false,
gulp_1       |   code: 'ERR_ASSERTION',
gulp_1       |   actual: false,
gulp_1       |   expected: true,
gulp_1       |   operator: '=='
gulp_1       | }
```

**Comment by phonoloop** [comment]
This might be a bit old by now but did you find a solution to this?

**Comment by utsavgupta** [comment]
Raised PR https://github.com/ellerbrock/docker-collection/pull/8
